#!/usr/bin/env python3
"""Generate src/gfx/sprites.{h,c} from the ASCII pixel art below.

Each glyph character maps to a palette entry; '.' is transparent.
Rows must be equal length. mirror=True mirrors the art horizontally
around its last column (draw the left half plus the centre column).

Run from the repository root:  python3 tools/gen_sprites.py
"""

import os

PALETTE = {
    '.': None,
    'W': (255, 255, 255),
    'S': (176, 180, 192),
    's': (96, 100, 116),
    'K': (28, 28, 40),
    'R': (255, 64, 64),
    'r': (170, 28, 28),
    'O': (255, 150, 40),
    'Y': (255, 220, 80),
    'G': (80, 255, 110),
    'g': (24, 150, 60),
    'C': (80, 220, 255),
    'c': (24, 120, 170),
    'B': (70, 100, 255),
    'b': (28, 40, 140),
    'M': (235, 80, 255),
    'm': (140, 30, 170),
    'P': (150, 70, 230),
    'p': (80, 30, 140),
    'T': (58, 68, 92),
}

SPRITES = {}


def sprite(name, art, mirror=False):
    rows = [r for r in art.strip('\n').split('\n')]
    w = len(rows[0])
    for r in rows:
        assert len(r) == w, f"{name}: ragged row {r!r}"
    if mirror:
        rows = [r + r[-2::-1] for r in rows]
    SPRITES[name] = rows


sprite('player', """
......W
.....CC
.....CW
....CCW
....CCW
.C..CCM
.CCCCCM
.CCcCCM
CCcCCCC
Cc..cOO
....OY.
""", mirror=True)

sprite('flame0', """
.O.
OYO
.O.
""")

sprite('flame1', """
.Y.
YWY
OYO
""")

sprite('drone', """
..G...
...G..
.GGGGG
GGgYgG
GGgGgG
.GGGGG
...G..
..G...
""", mirror=True)

sprite('darter', """
MM...
MMM..
.MMMM
.MMWM
..MWM
..MMM
...MM
...M.
....W
""", mirror=True)

sprite('sentry', """
....OOO
..OOOOO
.OOssss
OOsYYss
.OOssss
..OOOOO
....OOO
......s
.....ss
""", mirror=True)

sprite('roid_l', """
....SSSSSS....
..SSSsSSSSSS..
.SSSSSSSssSSS.
.SsSSSSSSSSSSS
SSSSSssSSSSSsS
SSsSSSSSSSSssS
SSSSSSSsSSSSSS
SsSSSsSSSSSSS.
.SSSSSSSSsSS..
.SSsSSSSSSSS..
..SSSSSsSS....
....SSSS......
""")

sprite('roid_s', """
..SSSS..
.SsSSSs.
SSSSsSSS
SSsSSSSS
.SSSSsS.
..SSSS..
""")

sprite('boss', """
..........PPPPPPPPPP
.......PPPTTTTTTTTTT
.....PPTTTTsssssssss
....PPTTsSSSSSSSSSSS
...PPTsSSSSSSSSSSSSS
..PPTsSSSSSSCCCCCCCC
..PTsSSSSSCCcccccccc
.PPTsSSSSCCccYYYYYYY
.PTsSSSSSCcYYYWWWWWW
.PTsSSSSSCcYYWWWWWWW
.PTsSSSSSCcYYYWWWWWW
.PPTsSSSSCCccYYYYYYY
..PTsSSSSSCCcccccccc
..PPTsSSSSSSCCCCCCCC
...PPTsSSSSSSSSSSSSS
....PPTTsSSSSSSSSSSS
.....PPTTTTsssssssss
.......PPPTTTTTTTTTT
..........PPPPPPPPPP
....O...............
...OYO..............
....O...............
""", mirror=True)

sprite('pu_spread', """
.YYYYYYY.
YKKKKKKKY
YKY.Y.YKY
YK.YYY.KY
YKY.Y.YKY
YK..Y..KY
YKKKKKKKY
.YYYYYYY.
""")

sprite('pu_rapid', """
.OOOOOOO.
OKKKKKKKO
OK..YY.KO
OK.YY..KO
OKYYYY.KO
OK..YY.KO
OKKKKKKKO
.OOOOOOO.
""")

sprite('pu_shield', """
.BBBBBBB.
BKKKKKKKB
BK.CCC.KB
BKC...CKB
BKC...CKB
BK.CCC.KB
BKKKKKKKB
.BBBBBBB.
""")

sprite('pu_bomb', """
.WWWWWWW.
WKKKKKKKW
WK..W..KW
WK.WWW.KW
WKWWWWWKW
WK.WWW.KW
WKKKKKKKW
.WWWWWWW.
""")

sprite('pu_life', """
.RRRRRRR.
RKKKKKKKR
RK.R.R.KR
RKRRRRRKR
RK.RRR.KR
RK..R..KR
RKKKKKKKR
.RRRRRRR.
""")

sprite('expl0', """
.....
..Y..
.YWY.
..Y..
.....
""")

sprite('expl1', """
..O..O..
.O.YY.O.
..YWWY..
.OYWWYO.
..YWWY..
.O.YY.O.
..O..O..
........
""")

sprite('expl2', """
.r..O..r..
O..r.r..O.
..O...O...
.r..r..r..
O....r...O
..r...O...
.O..r..O..
..........
""")

sprite('heart', """
.RR.RR.
RRRRRRR
RRRRRRR
.RRRRR.
..RRR..
...R...
""")

sprite('bomb_icon', """
..WW..
.WWWW.
WWWWWW
WWWWWW
.WWWW.
..WW..
""")


def rgb565(rgb):
    r, g, b = rgb
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    chars = list(PALETTE.keys())  # '.' first -> index 0 transparent

    h = ["// Generated by tools/gen_sprites.py - edit the art there, not here.",
         "#ifndef NOVA_SPRITES_H", "#define NOVA_SPRITES_H", "",
         '#include "gfx/gfx.h"', "",
         f"extern const uint16_t sprite_palette[{len(chars)}];", ""]
    c = ["// Generated by tools/gen_sprites.py - edit the art there, not here.",
         '#include "gfx/sprites.h"', "",
         f"const uint16_t sprite_palette[{len(chars)}] = {{"]
    pal_entries = []
    for ch in chars:
        v = rgb565(PALETTE[ch]) if PALETTE[ch] else 0
        pal_entries.append(f"0x{v:04X}")
    c.append("    " + ", ".join(pal_entries))
    c.append("};\n")

    for name, rows in SPRITES.items():
        w, hgt = len(rows[0]), len(rows)
        c.append(f"static const uint8_t px_{name}[{w * hgt}] = {{")
        for row in rows:
            vals = [str(chars.index(ch)) for ch in row]
            c.append("    " + ",".join(vals) + ",")
        c.append("};")
        c.append(f"const sprite_t spr_{name} = {{ {w}, {hgt}, px_{name} }};\n")
        h.append(f"extern const sprite_t spr_{name};")

    h += ["", "#endif", ""]

    with open(os.path.join(root, "src/gfx/sprites.h"), "w") as f:
        f.write("\n".join(h))
    with open(os.path.join(root, "src/gfx/sprites.c"), "w") as f:
        f.write("\n".join(c) + "\n")
    print(f"wrote {len(SPRITES)} sprites")


if __name__ == "__main__":
    main()
