// Generated by tools/gen_sprites.py - edit the art there, not here.
#ifndef NOVA_SPRITES_H
#define NOVA_SPRITES_H

#include "gfx/gfx.h"

extern const uint16_t sprite_palette[20];

extern const sprite_t spr_player;
extern const sprite_t spr_flame0;
extern const sprite_t spr_flame1;
extern const sprite_t spr_drone;
extern const sprite_t spr_darter;
extern const sprite_t spr_sentry;
extern const sprite_t spr_roid_l;
extern const sprite_t spr_roid_s;
extern const sprite_t spr_boss;
extern const sprite_t spr_pu_spread;
extern const sprite_t spr_pu_rapid;
extern const sprite_t spr_pu_shield;
extern const sprite_t spr_pu_bomb;
extern const sprite_t spr_pu_life;
extern const sprite_t spr_expl0;
extern const sprite_t spr_expl1;
extern const sprite_t spr_expl2;
extern const sprite_t spr_heart;
extern const sprite_t spr_bomb_icon;

#endif
